project:
  type: website
  output-dir: docs

website:
  title: "めもちょう"
  navbar:
    right:
      - about.qmd
      # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
  search: 
    location: navbar
    type: overlay

  open-graph: true
  twitter-card: true

format:
  html:
    theme: minty
    css: styles.css
    date-format: "YYYY 年 MM 月 DD 日"
    # include-in-header:
    #       - text: |
    #           <meta name="google-site-verification" content="cZPHfzzSIV8ZFPkWH0DArBxWrk-Ulb5g_1572IGYSy8" />

execute:
  freeze: auto

copyright: "Copyright tamuraup. 2024. All Rights Reserved"
